### ISSUE TITLE
Directed-weighted network community detection

### ISSUE THREAD

**Issue by huangJianwei1119** [nicolasdugue/DirectedLouvain#4]
Hi,

I have compiled your code on my computer and it works. However, I only find the command to run the program for a weighted network (i.e., ./convert -i graph.txt -o graph.bin -w graph.weights). My question is:

What is the command to run the program for a weighted-directed network? Further, how can I find the output with node name and community number?

Thank you!

**Comment by rbisariya** [comment]
> Hi,
> 
> I have compiled your code on my computer and it works. However, I only find the command to run the program for a weighted network (i.e., ./convert -i graph.txt -o graph.bin -w graph.weights). My question is:
> 
> What is the command to run the program for a weighted-directed network? Further, how can I find the output with node name and community number?
> 
> Thank you!

Hey, how did you compile/run the code?

Thanks in advance!
