### ISSUE TITLE
How do I use this software?

### ISSUE THREAD

**Issue by rbisariya** [nicolasdugue/DirectedLouvain#5]
Hi!

Thank you for creating this software. I really needed a modified Louvain Algo for directed graphs and this looks to be the answer. However, I don't understand how to run the software. Can you please quickly give me instructions on what to do? I have the necessary artifacts but I just don't know how to use this code. 

Thanks,
Rohan

**Comment by nicolasdugue** [comment]
Hi !
What do you need ? The Readme describes how to run the code : https://github.com/nicolasdugue/DirectedLouvain/blob/master/README.md

**Comment by rbisariya** [comment]
Not sure how to compile the software as it is different than what readme says.
 
 
  On Mon, Nov 23, 2020 at 1:21 AM, Nico<notifications@github.com> wrote:   


Reopened #5.

**Comment by nicolasdugue** [comment]
You can use the `make` command at the root of the software to compile the project.
