### ISSUE TITLE
Preserving order with convert's -r tag

### ISSUE THREAD

**Issue by jmasom** [nicolasdugue/DirectedLouvain#7]
So I ran convert on an edge list file where nodes were 8 digit IDs. Without using the -r tag, the binary representation of the graph had ~40mil nodes, but I know that the graph is only supposed to have ~300k, so I re-ran it with -r. The help message for this tag says "the order is kept". My question is, what notion of order does this refer to? Is it order of appearance in the edge list file, or is it numerical order of the original IDs? For example, with this edge list:
200 100
100 300

would the renumbered node set be this:
200 -> 0
100 -> 1
300 -> 2

or this:
100 -> 0
200 -> 1
300 -> 2

**Comment by nicolasdugue** [comment]
Hi !
It uses the order of appearance in the edge list, so it would be
```
200 0
100 1
300 2
```
